export const ENVConfig = {
  API_URL: process.env.NEXT_PUBLIC_LINK_API,
  APP_KEY: process.env.NEXT_PUBLIC_APP_KEY,
  APP_SECRET: process.env.NEXT_PUBLIC_APP_SECRET,
  APP_PROVIDER: process.env.NEXT_PUBLIC_APP_PROVIDER,
  APP_CLIENT_ID: process.env.NEXT_PUBLIC_APP_CLIENT_ID,
  VERSION_NAME: process.env.NEXT_PUBLIC_VERSION_NAME,
  GOOGLE_MAP_KEY: process.env.NEXT_PUBLIC_GOOGLE_MAP_KEY,
  ENV: process.env.NEXT_PUBLIC_ENV,
  CLEVERTAP_KEY: process.env.NEXT_PUBLIC_CLEVERTAP_KEY
};
