name: Deploy to Dev Server

on:
  push:
    branches:
      - auto-build # Trigger workflow on push to auto-build

jobs:
  build-and-publish:
    runs-on: ubuntu-22.04-arm
    steps:
      # Step 1: Checkout the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify the Node.js version you want to use

      # Step 3: Setup SSH key
      - name: Setup SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519

      # Step 4: Setup cloudflared for ARM64 and Test Connection to Server
      - name: Setup cloudflared
        run: |
          curl -L https://github.com/cloudflare/cloudflared/releases/latest/download/cloudflared-linux-arm64.deb -o cloudflared.deb
          sudo dpkg -i cloudflared.deb
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o "ProxyCommand=cloudflared access ssh --hostname ${{ secrets.SSH_HOSTNAME }}" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }} 
          echo '✅ SSH kết nối thành công qua Cloudflare Tunnel'
          touch test.txt
          scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o "ProxyCommand=cloudflared access ssh --hostname ${{ secrets.SSH_HOSTNAME }}" test.txt ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}:"/home/${{ secrets.SSH_USER }}/Projects/tmp/htc/${{ vars.APP_NAME }}" 
          echo '✅ SCP thành công qua Cloudflare Tunnel'

      # Step 5: Install dependencies
      - name: Install dependencies
        run: |
          yarn install --omit=dev

      # Step 6: Build the app
      - name: Build the app
        run: |
          yarn build

      # Step 7: Zip all necessary files in a build directory
      - name: Zip the build files
        run: |
          mkdir -p output
          [ -d public ] && mv public output/ 
          mv .next node_modules pm2.config.js package.json output/
          zip -r build.zip output/

      # Step 8: Copy file to server via Cloudflare SSH
      - name: Copy file to server via Cloudflare SSH
        run: |
          scp -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o "ProxyCommand=cloudflared access ssh --hostname ${{ secrets.SSH_HOSTNAME }}" build.zip ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }}:"/home/${{ secrets.SSH_USER }}/Projects/tmp/htc/${{ vars.APP_NAME }}"

      # Step 9: SSH & Deploy on Server
      - name: SSH & Deploy on Server
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no -o "ProxyCommand=cloudflared access ssh --hostname ${{ secrets.SSH_HOSTNAME }}" ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOSTNAME }} << 'EOF'
          unzip -o /home/${USER}/Projects/tmp/htc/${{ vars.APP_NAME }}/build.zip -d /home/${USER}/Projects/htc/
          cd /home/${USER}/Projects/htc
          [ -d ${{ vars.APP_NAME }} ] && zip -r /home/${USER}/Projects/bak/htc/${{ vars.APP_NAME }}.zip ${{ vars.APP_NAME }}
          [ -d ${{ vars.APP_NAME }} ] && rm -rf ${{ vars.APP_NAME }}
          mv output ${{ vars.APP_NAME }}
          cd ${{ vars.APP_NAME }}
          if pm2 describe ${{ vars.APP_NAME }} > /dev/null; then echo "Ứng dụng đang chạy, thực hiện restart..."; pm2 restart ${{ vars.APP_NAME }}; else echo "Ứng dụng chưa được khởi động, thực hiện start..."; pm2 start pm2.config.js; fi
          EOF
